cmd_arch/um/kernel/config.o := gcc -Wp,-MD,arch/um/kernel/.config.o.d  -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Os -mcmodel=large -fno-builtin -m64 -funit-at-a-time -D__arch_um__ -Dvmap=kernel_vmap -Din6addr_loopback=kernel_in6addr_loopback -Din6addr_any=kernel_in6addr_any -Dstrrchr=kernel_strrchr -D_LARGEFILE64_SOURCE  -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -I/home/valerian/Documents/ba6/OS/repo/Scheduler/linux-3.8.3/arch/um/include/shared -I/home/valerian/Documents/ba6/OS/repo/Scheduler/linux-3.8.3/arch/x86/um/shared -I/home/valerian/Documents/ba6/OS/repo/Scheduler/linux-3.8.3/arch/um/include/shared/skas  -D_FILE_OFFSET_BITS=64 -idirafter include -D_GNU_SOURCE -D_LARGEFILE64_SOURCE -include /home/valerian/Documents/ba6/OS/repo/Scheduler/linux-3.8.3/include/linux/kern_levels.h -include user.h  -c -o arch/um/kernel/config.o arch/um/kernel/config.c

source_arch/um/kernel/config.o := arch/um/kernel/config.c

deps_arch/um/kernel/config.o := \
    $(wildcard include/config/defconfig/list.h) \
    $(wildcard include/config/list.h) \
    $(wildcard include/config/uml.h) \
    $(wildcard include/config/mmu.h) \
    $(wildcard include/config/no/iomem.h) \
    $(wildcard include/config/trace/irqflags/support.h) \
    $(wildcard include/config/lockdep/support.h) \
    $(wildcard include/config/stacktrace/support.h) \
    $(wildcard include/config/generic/calibrate/delay.h) \
    $(wildcard include/config/generic/bug.h) \
    $(wildcard include/config/hz.h) \
    $(wildcard include/config/mk8.h) \
    $(wildcard include/config/mpsc.h) \
    $(wildcard include/config/mcore2.h) \
    $(wildcard include/config/matom.h) \
    $(wildcard include/config/generic/cpu.h) \
    $(wildcard include/config/x86/internode/cache/shift.h) \
    $(wildcard include/config/x86/l1/cache/shift.h) \
    $(wildcard include/config/x86/tsc.h) \
    $(wildcard include/config/x86/cmpxchg64.h) \
    $(wildcard include/config/x86/cmov.h) \
    $(wildcard include/config/x86/minimum/cpu/family.h) \
    $(wildcard include/config/cpu/sup/intel.h) \
    $(wildcard include/config/cpu/sup/amd.h) \
    $(wildcard include/config/cpu/sup/centaur.h) \
    $(wildcard include/config/uml/x86.h) \
    $(wildcard include/config/64bit.h) \
    $(wildcard include/config/x86/32.h) \
    $(wildcard include/config/x86/64.h) \
    $(wildcard include/config/rwsem/xchgadd/algorithm.h) \
    $(wildcard include/config/rwsem/generic/spinlock.h) \
    $(wildcard include/config/3/level/pgtables.h) \
    $(wildcard include/config/arch/has/sc/signals.h) \
    $(wildcard include/config/arch/reuse/host/vsyscall/area.h) \
    $(wildcard include/config/generic/hweight.h) \
    $(wildcard include/config/static/link.h) \
    $(wildcard include/config/select/memory/model.h) \
    $(wildcard include/config/flatmem/manual.h) \
    $(wildcard include/config/flatmem.h) \
    $(wildcard include/config/flat/node/mem/map.h) \
    $(wildcard include/config/pageflags/extended.h) \
    $(wildcard include/config/split/ptlock/cpus.h) \
    $(wildcard include/config/compaction.h) \
    $(wildcard include/config/phys/addr/t/64bit.h) \
    $(wildcard include/config/zone/dma/flag.h) \
    $(wildcard include/config/virt/to/bus.h) \
    $(wildcard include/config/ksm.h) \
    $(wildcard include/config/default/mmap/min/addr.h) \
    $(wildcard include/config/cross/memory/attach.h) \
    $(wildcard include/config/need/per/cpu/km.h) \
    $(wildcard include/config/cleancache.h) \
    $(wildcard include/config/frontswap.h) \
    $(wildcard include/config/ld/script/dyn.h) \
    $(wildcard include/config/binfmt/elf.h) \
    $(wildcard include/config/core/dump/default/elf/headers.h) \
    $(wildcard include/config/have/aout.h) \
    $(wildcard include/config/binfmt/misc.h) \
    $(wildcard include/config/coredump.h) \
    $(wildcard include/config/hostfs.h) \
    $(wildcard include/config/hppfs.h) \
    $(wildcard include/config/mconsole.h) \
    $(wildcard include/config/magic/sysrq.h) \
    $(wildcard include/config/kernel/stack/order.h) \
    $(wildcard include/config/mmapper.h) \
    $(wildcard include/config/no/dma.h) \
    $(wildcard include/config/experimental.h) \
    $(wildcard include/config/broken/on/smp.h) \
    $(wildcard include/config/init/env/arg/limit.h) \
    $(wildcard include/config/cross/compile.h) \
    $(wildcard include/config/localversion.h) \
    $(wildcard include/config/localversion/auto.h) \
    $(wildcard include/config/default/hostname.h) \
    $(wildcard include/config/swap.h) \
    $(wildcard include/config/sysvipc.h) \
    $(wildcard include/config/sysvipc/sysctl.h) \
    $(wildcard include/config/posix/mqueue.h) \
    $(wildcard include/config/posix/mqueue/sysctl.h) \
    $(wildcard include/config/fhandle.h) \
    $(wildcard include/config/audit.h) \
    $(wildcard include/config/have/generic/hardirqs.h) \
    $(wildcard include/config/generic/hardirqs.h) \
    $(wildcard include/config/generic/irq/show.h) \
    $(wildcard include/config/generic/clockevents.h) \
    $(wildcard include/config/generic/clockevents/build.h) \
    $(wildcard include/config/tick/oneshot.h) \
    $(wildcard include/config/no/hz.h) \
    $(wildcard include/config/high/res/timers.h) \
    $(wildcard include/config/tick/cpu/accounting.h) \
    $(wildcard include/config/bsd/process/acct.h) \
    $(wildcard include/config/bsd/process/acct/v3.h) \
    $(wildcard include/config/taskstats.h) \
    $(wildcard include/config/tiny/rcu.h) \
    $(wildcard include/config/preempt/rcu.h) \
    $(wildcard include/config/tree/rcu/trace.h) \
    $(wildcard include/config/ikconfig.h) \
    $(wildcard include/config/ikconfig/proc.h) \
    $(wildcard include/config/proc.h) \
    $(wildcard include/config/log/buf/shift.h) \
    $(wildcard include/config/cgroups.h) \
    $(wildcard include/config/cgroup/debug.h) \
    $(wildcard include/config/cgroup/freezer.h) \
    $(wildcard include/config/cgroup/device.h) \
    $(wildcard include/config/cpusets.h) \
    $(wildcard include/config/proc/pid/cpuset.h) \
    $(wildcard include/config/cgroup/cpuacct.h) \
    $(wildcard include/config/resource/counters.h) \
    $(wildcard include/config/memcg.h) \
    $(wildcard include/config/cgroup/sched.h) \
    $(wildcard include/config/fair/group/sched.h) \
    $(wildcard include/config/cfs/bandwidth.h) \
    $(wildcard include/config/rt/group/sched.h) \
    $(wildcard include/config/blk/cgroup.h) \
    $(wildcard include/config/debug/blk/cgroup.h) \
    $(wildcard include/config/checkpoint/restore.h) \
    $(wildcard include/config/namespaces.h) \
    $(wildcard include/config/uts/ns.h) \
    $(wildcard include/config/ipc/ns.h) \
    $(wildcard include/config/user/ns.h) \
    $(wildcard include/config/pid/ns.h) \
    $(wildcard include/config/net/ns.h) \
    $(wildcard include/config/uidgid/converted.h) \
    $(wildcard include/config/uidgid/strict/type/checks.h) \
    $(wildcard include/config/sched/autogroup.h) \
    $(wildcard include/config/sysfs/deprecated.h) \
    $(wildcard include/config/sysfs/deprecated/v2.h) \
    $(wildcard include/config/relay.h) \
    $(wildcard include/config/blk/dev/initrd.h) \
    $(wildcard include/config/cc/optimize/for/size.h) \
    $(wildcard include/config/sysctl.h) \
    $(wildcard include/config/anon/inodes.h) \
    $(wildcard include/config/expert.h) \
    $(wildcard include/config/have/uid16.h) \
    $(wildcard include/config/uid16.h) \
    $(wildcard include/config/sysctl/syscall.h) \
    $(wildcard include/config/kallsyms.h) \
    $(wildcard include/config/kallsyms/all.h) \
    $(wildcard include/config/hotplug.h) \
    $(wildcard include/config/printk.h) \
    $(wildcard include/config/bug.h) \
    $(wildcard include/config/elf/core.h) \
    $(wildcard include/config/base/full.h) \
    $(wildcard include/config/futex.h) \
    $(wildcard include/config/epoll.h) \
    $(wildcard include/config/signalfd.h) \
    $(wildcard include/config/timerfd.h) \
    $(wildcard include/config/eventfd.h) \
    $(wildcard include/config/shmem.h) \
    $(wildcard include/config/aio.h) \
    $(wildcard include/config/embedded.h) \
    $(wildcard include/config/vm/event/counters.h) \
    $(wildcard include/config/compat/brk.h) \
    $(wildcard include/config/slab.h) \
    $(wildcard include/config/slub.h) \
    $(wildcard include/config/profiling.h) \
    $(wildcard include/config/modules/use/elf/rela.h) \
    $(wildcard include/config/generic/sigaltstack.h) \
    $(wildcard include/config/have/generic/dma/coherent.h) \
    $(wildcard include/config/slabinfo.h) \
    $(wildcard include/config/rt/mutexes.h) \
    $(wildcard include/config/base/small.h) \
    $(wildcard include/config/modules.h) \
    $(wildcard include/config/module/force/load.h) \
    $(wildcard include/config/module/unload.h) \
    $(wildcard include/config/module/force/unload.h) \
    $(wildcard include/config/modversions.h) \
    $(wildcard include/config/module/srcversion/all.h) \
    $(wildcard include/config/module/sig.h) \
    $(wildcard include/config/block.h) \
    $(wildcard include/config/blk/dev/bsg.h) \
    $(wildcard include/config/blk/dev/bsglib.h) \
    $(wildcard include/config/blk/dev/integrity.h) \
    $(wildcard include/config/blk/dev/throttling.h) \
    $(wildcard include/config/partition/advanced.h) \
    $(wildcard include/config/msdos/partition.h) \
    $(wildcard include/config/efi/partition.h) \
    $(wildcard include/config/iosched/noop.h) \
    $(wildcard include/config/iosched/deadline.h) \
    $(wildcard include/config/iosched/cfq.h) \
    $(wildcard include/config/cfq/group/iosched.h) \
    $(wildcard include/config/default/deadline.h) \
    $(wildcard include/config/default/noop.h) \
    $(wildcard include/config/default/iosched.h) \
    $(wildcard include/config/inline/spin/unlock/irq.h) \
    $(wildcard include/config/inline/read/unlock.h) \
    $(wildcard include/config/inline/read/unlock/irq.h) \
    $(wildcard include/config/inline/write/unlock.h) \
    $(wildcard include/config/inline/write/unlock/irq.h) \
    $(wildcard include/config/freezer.h) \
    $(wildcard include/config/stderr/console.h) \
    $(wildcard include/config/stdio/console.h) \
    $(wildcard include/config/ssl.h) \
    $(wildcard include/config/null/chan.h) \
    $(wildcard include/config/port/chan.h) \
    $(wildcard include/config/pty/chan.h) \
    $(wildcard include/config/tty/chan.h) \
    $(wildcard include/config/xterm/chan.h) \
    $(wildcard include/config/noconfig/chan.h) \
    $(wildcard include/config/chan.h) \
    $(wildcard include/config/con/zero/chan.h) \
    $(wildcard include/config/con/chan.h) \
    $(wildcard include/config/ssl/chan.h) \
    $(wildcard include/config/uml/sound.h) \
    $(wildcard include/config/sound.h) \
    $(wildcard include/config/sound/oss/core.h) \
    $(wildcard include/config/hostaudio.h) \
    $(wildcard include/config/uevent/helper/path.h) \
    $(wildcard include/config/devtmpfs.h) \
    $(wildcard include/config/devtmpfs/mount.h) \
    $(wildcard include/config/standalone.h) \
    $(wildcard include/config/prevent/firmware/build.h) \
    $(wildcard include/config/fw/loader.h) \
    $(wildcard include/config/firmware/in/kernel.h) \
    $(wildcard include/config/extra/firmware.h) \
    $(wildcard include/config/debug/driver.h) \
    $(wildcard include/config/debug/devres.h) \
    $(wildcard include/config/sys/hypervisor.h) \
    $(wildcard include/config/generic/cpu/devices.h) \
    $(wildcard include/config/dma/shared/buffer.h) \
    $(wildcard include/config/connector.h) \
    $(wildcard include/config/mtd.h) \
    $(wildcard include/config/blk/dev.h) \
    $(wildcard include/config/blk/dev/ubd.h) \
    $(wildcard include/config/blk/dev/ubd/sync.h) \
    $(wildcard include/config/blk/dev/cow/common.h) \
    $(wildcard include/config/blk/dev/loop.h) \
    $(wildcard include/config/blk/dev/loop/min/count.h) \
    $(wildcard include/config/blk/dev/cryptoloop.h) \
    $(wildcard include/config/blk/dev/drbd.h) \
    $(wildcard include/config/blk/dev/nbd.h) \
    $(wildcard include/config/blk/dev/ram.h) \
    $(wildcard include/config/ata/over/eth.h) \
    $(wildcard include/config/blk/dev/rbd.h) \
    $(wildcard include/config/enclosure/services.h) \
    $(wildcard include/config/c2port.h) \
    $(wildcard include/config/eeprom/93cx6.h) \
    $(wildcard include/config/scsi/mod.h) \
    $(wildcard include/config/raid/attrs.h) \
    $(wildcard include/config/scsi.h) \
    $(wildcard include/config/scsi/dma.h) \
    $(wildcard include/config/scsi/netlink.h) \
    $(wildcard include/config/md.h) \
    $(wildcard include/config/netdevices.h) \
    $(wildcard include/config/net/core.h) \
    $(wildcard include/config/bonding.h) \
    $(wildcard include/config/dummy.h) \
    $(wildcard include/config/equalizer.h) \
    $(wildcard include/config/mii.h) \
    $(wildcard include/config/net/team.h) \
    $(wildcard include/config/macvlan.h) \
    $(wildcard include/config/vxlan.h) \
    $(wildcard include/config/netconsole.h) \
    $(wildcard include/config/netpoll.h) \
    $(wildcard include/config/net/poll/controller.h) \
    $(wildcard include/config/tun.h) \
    $(wildcard include/config/veth.h) \
    $(wildcard include/config/net/dsa/mv88e6xxx.h) \
    $(wildcard include/config/net/dsa/mv88e6060.h) \
    $(wildcard include/config/net/dsa/mv88e6xxx/need/ppu.h) \
    $(wildcard include/config/net/dsa/mv88e6131.h) \
    $(wildcard include/config/net/dsa/mv88e6123/61/65.h) \
    $(wildcard include/config/ethernet.h) \
    $(wildcard include/config/net/vendor/intel.h) \
    $(wildcard include/config/net/vendor/i825xx.h) \
    $(wildcard include/config/net/vendor/marvell.h) \
    $(wildcard include/config/mvmdio.h) \
    $(wildcard include/config/net/vendor/natsemi.h) \
    $(wildcard include/config/net/vendor/8390.h) \
    $(wildcard include/config/phylib.h) \
    $(wildcard include/config/ppp.h) \
    $(wildcard include/config/ppp/bsdcomp.h) \
    $(wildcard include/config/ppp/deflate.h) \
    $(wildcard include/config/ppp/filter.h) \
    $(wildcard include/config/ppp/mppe.h) \
    $(wildcard include/config/ppp/multilink.h) \
    $(wildcard include/config/pppoe.h) \
    $(wildcard include/config/ppp/async.h) \
    $(wildcard include/config/ppp/sync/tty.h) \
    $(wildcard include/config/slip.h) \
    $(wildcard include/config/slhc.h) \
    $(wildcard include/config/slip/compressed.h) \
    $(wildcard include/config/slip/smart.h) \
    $(wildcard include/config/slip/mode/slip6.h) \
    $(wildcard include/config/wlan.h) \
    $(wildcard include/config/hostap.h) \
    $(wildcard include/config/wl/ti.h) \
    $(wildcard include/config/wan.h) \
    $(wildcard include/config/unix98/ptys.h) \
    $(wildcard include/config/devpts/multiple/instances.h) \
    $(wildcard include/config/legacy/ptys.h) \
    $(wildcard include/config/legacy/pty/count.h) \
    $(wildcard include/config/n/gsm.h) \
    $(wildcard include/config/trace/sink.h) \
    $(wildcard include/config/devkmem.h) \
    $(wildcard include/config/hw/random.h) \
    $(wildcard include/config/uml/random.h) \
    $(wildcard include/config/r3964.h) \
    $(wildcard include/config/raw/driver.h) \
    $(wildcard include/config/i2c.h) \
    $(wildcard include/config/hsi.h) \
    $(wildcard include/config/pps.h) \
    $(wildcard include/config/ptp/1588/clock.h) \
    $(wildcard include/config/ptp/1588/clock/pch.h) \
    $(wildcard include/config/power/supply.h) \
    $(wildcard include/config/power/avs.h) \
    $(wildcard include/config/thermal.h) \
    $(wildcard include/config/watchdog.h) \
    $(wildcard include/config/regulator.h) \
    $(wildcard include/config/sound/oss/core/preclaim.h) \
    $(wildcard include/config/usb/arch/has/ohci.h) \
    $(wildcard include/config/usb/arch/has/ehci.h) \
    $(wildcard include/config/usb/arch/has/xhci.h) \
    $(wildcard include/config/memstick.h) \
    $(wildcard include/config/new/leds.h) \
    $(wildcard include/config/accessibility.h) \
    $(wildcard include/config/auxdisplay.h) \
    $(wildcard include/config/uio.h) \
    $(wildcard include/config/staging.h) \
    $(wildcard include/config/iommu/support.h) \
    $(wildcard include/config/virt/drivers.h) \
    $(wildcard include/config/pm/devfreq.h) \
    $(wildcard include/config/extcon.h) \
    $(wildcard include/config/memory.h) \
    $(wildcard include/config/iio.h) \
    $(wildcard include/config/pwm.h) \
    $(wildcard include/config/net.h) \
    $(wildcard include/config/packet.h) \
    $(wildcard include/config/packet/diag.h) \
    $(wildcard include/config/unix.h) \
    $(wildcard include/config/unix/diag.h) \
    $(wildcard include/config/xfrm.h) \
    $(wildcard include/config/xfrm/user.h) \
    $(wildcard include/config/xfrm/sub/policy.h) \
    $(wildcard include/config/xfrm/migrate.h) \
    $(wildcard include/config/xfrm/statistics.h) \
    $(wildcard include/config/net/key.h) \
    $(wildcard include/config/inet.h) \
    $(wildcard include/config/ip/multicast.h) \
    $(wildcard include/config/ip/advanced/router.h) \
    $(wildcard include/config/ip/pnp.h) \
    $(wildcard include/config/net/ipip.h) \
    $(wildcard include/config/net/ipgre/demux.h) \
    $(wildcard include/config/arpd.h) \
    $(wildcard include/config/syn/cookies.h) \
    $(wildcard include/config/net/ipvti.h) \
    $(wildcard include/config/inet/ah.h) \
    $(wildcard include/config/inet/esp.h) \
    $(wildcard include/config/inet/ipcomp.h) \
    $(wildcard include/config/inet/xfrm/tunnel.h) \
    $(wildcard include/config/inet/tunnel.h) \
    $(wildcard include/config/inet/xfrm/mode/transport.h) \
    $(wildcard include/config/inet/xfrm/mode/tunnel.h) \
    $(wildcard include/config/inet/xfrm/mode/beet.h) \
    $(wildcard include/config/inet/lro.h) \
    $(wildcard include/config/inet/diag.h) \
    $(wildcard include/config/inet/tcp/diag.h) \
    $(wildcard include/config/inet/udp/diag.h) \
    $(wildcard include/config/tcp/cong/advanced.h) \
    $(wildcard include/config/tcp/cong/cubic.h) \
    $(wildcard include/config/default/tcp/cong.h) \
    $(wildcard include/config/tcp/md5sig.h) \
    $(wildcard include/config/ipv6.h) \
    $(wildcard include/config/network/secmark.h) \
    $(wildcard include/config/network/phy/timestamping.h) \
    $(wildcard include/config/netfilter.h) \
    $(wildcard include/config/ip/dccp.h) \
    $(wildcard include/config/ip/sctp.h) \
    $(wildcard include/config/rds.h) \
    $(wildcard include/config/tipc.h) \
    $(wildcard include/config/atm.h) \
    $(wildcard include/config/l2tp.h) \
    $(wildcard include/config/bridge.h) \
    $(wildcard include/config/have/net/dsa.h) \
    $(wildcard include/config/vlan/8021q.h) \
    $(wildcard include/config/decnet.h) \
    $(wildcard include/config/llc2.h) \
    $(wildcard include/config/ipx.h) \
    $(wildcard include/config/atalk.h) \
    $(wildcard include/config/x25.h) \
    $(wildcard include/config/lapb.h) \
    $(wildcard include/config/wan/router.h) \
    $(wildcard include/config/phonet.h) \
    $(wildcard include/config/ieee802154.h) \
    $(wildcard include/config/net/sched.h) \
    $(wildcard include/config/dcb.h) \
    $(wildcard include/config/batman/adv.h) \
    $(wildcard include/config/openvswitch.h) \
    $(wildcard include/config/netprio/cgroup.h) \
    $(wildcard include/config/bql.h) \
    $(wildcard include/config/net/pktgen.h) \
    $(wildcard include/config/hamradio.h) \
    $(wildcard include/config/can.h) \
    $(wildcard include/config/irda.h) \
    $(wildcard include/config/bt.h) \
    $(wildcard include/config/af/rxrpc.h) \
    $(wildcard include/config/wireless.h) \
    $(wildcard include/config/cfg80211.h) \
    $(wildcard include/config/lib80211.h) \
    $(wildcard include/config/wimax.h) \
    $(wildcard include/config/rfkill.h) \
    $(wildcard include/config/net/9p.h) \
    $(wildcard include/config/caif.h) \
    $(wildcard include/config/ceph/lib.h) \
    $(wildcard include/config/nfc.h) \
    $(wildcard include/config/uml/net.h) \
    $(wildcard include/config/uml/net/ethertap.h) \
    $(wildcard include/config/uml/net/tuntap.h) \
    $(wildcard include/config/uml/net/slip.h) \
    $(wildcard include/config/uml/net/daemon.h) \
    $(wildcard include/config/uml/net/vde.h) \
    $(wildcard include/config/uml/net/mcast.h) \
    $(wildcard include/config/uml/net/pcap.h) \
    $(wildcard include/config/uml/net/slirp.h) \
    $(wildcard include/config/ext2/fs.h) \
    $(wildcard include/config/ext3/fs.h) \
    $(wildcard include/config/ext4/fs.h) \
    $(wildcard include/config/ext4/use/for/ext23.h) \
    $(wildcard include/config/ext4/fs/posix/acl.h) \
    $(wildcard include/config/ext4/fs/security.h) \
    $(wildcard include/config/ext4/debug.h) \
    $(wildcard include/config/jbd2.h) \
    $(wildcard include/config/fs/mbcache.h) \
    $(wildcard include/config/reiserfs/fs.h) \
    $(wildcard include/config/reiserfs/check.h) \
    $(wildcard include/config/reiserfs/proc/info.h) \
    $(wildcard include/config/reiserfs/fs/xattr.h) \
    $(wildcard include/config/jfs/fs.h) \
    $(wildcard include/config/xfs/fs.h) \
    $(wildcard include/config/gfs2/fs.h) \
    $(wildcard include/config/btrfs/fs.h) \
    $(wildcard include/config/nilfs2/fs.h) \
    $(wildcard include/config/fs/posix/acl.h) \
    $(wildcard include/config/file/locking.h) \
    $(wildcard include/config/fsnotify.h) \
    $(wildcard include/config/dnotify.h) \
    $(wildcard include/config/inotify/user.h) \
    $(wildcard include/config/fanotify.h) \
    $(wildcard include/config/quota.h) \
    $(wildcard include/config/quota/netlink/interface.h) \
    $(wildcard include/config/print/quota/warning.h) \
    $(wildcard include/config/quota/debug.h) \
    $(wildcard include/config/qfmt/v1.h) \
    $(wildcard include/config/qfmt/v2.h) \
    $(wildcard include/config/quotactl.h) \
    $(wildcard include/config/autofs4/fs.h) \
    $(wildcard include/config/fuse/fs.h) \
    $(wildcard include/config/fscache.h) \
    $(wildcard include/config/iso9660/fs.h) \
    $(wildcard include/config/joliet.h) \
    $(wildcard include/config/zisofs.h) \
    $(wildcard include/config/udf/fs.h) \
    $(wildcard include/config/msdos/fs.h) \
    $(wildcard include/config/vfat/fs.h) \
    $(wildcard include/config/ntfs/fs.h) \
    $(wildcard include/config/proc/fs.h) \
    $(wildcard include/config/proc/kcore.h) \
    $(wildcard include/config/proc/sysctl.h) \
    $(wildcard include/config/proc/page/monitor.h) \
    $(wildcard include/config/sysfs.h) \
    $(wildcard include/config/tmpfs.h) \
    $(wildcard include/config/tmpfs/posix/acl.h) \
    $(wildcard include/config/tmpfs/xattr.h) \
    $(wildcard include/config/hugetlb/page.h) \
    $(wildcard include/config/configfs/fs.h) \
    $(wildcard include/config/misc/filesystems.h) \
    $(wildcard include/config/adfs/fs.h) \
    $(wildcard include/config/affs/fs.h) \
    $(wildcard include/config/hfs/fs.h) \
    $(wildcard include/config/hfsplus/fs.h) \
    $(wildcard include/config/befs/fs.h) \
    $(wildcard include/config/bfs/fs.h) \
    $(wildcard include/config/efs/fs.h) \
    $(wildcard include/config/logfs.h) \
    $(wildcard include/config/cramfs.h) \
    $(wildcard include/config/squashfs.h) \
    $(wildcard include/config/vxfs/fs.h) \
    $(wildcard include/config/minix/fs.h) \
    $(wildcard include/config/omfs/fs.h) \
    $(wildcard include/config/hpfs/fs.h) \
    $(wildcard include/config/qnx4fs/fs.h) \
    $(wildcard include/config/qnx6fs/fs.h) \
    $(wildcard include/config/romfs/fs.h) \
    $(wildcard include/config/pstore.h) \
    $(wildcard include/config/sysv/fs.h) \
    $(wildcard include/config/ufs/fs.h) \
    $(wildcard include/config/f2fs/fs.h) \
    $(wildcard include/config/network/filesystems.h) \
    $(wildcard include/config/nfs/fs.h) \
    $(wildcard include/config/nfsd.h) \
    $(wildcard include/config/ceph/fs.h) \
    $(wildcard include/config/cifs.h) \
    $(wildcard include/config/ncp/fs.h) \
    $(wildcard include/config/coda/fs.h) \
    $(wildcard include/config/afs/fs.h) \
    $(wildcard include/config/nls.h) \
    $(wildcard include/config/nls/default.h) \
    $(wildcard include/config/nls/codepage/437.h) \
    $(wildcard include/config/nls/codepage/737.h) \
    $(wildcard include/config/nls/codepage/775.h) \
    $(wildcard include/config/nls/codepage/850.h) \
    $(wildcard include/config/nls/codepage/852.h) \
    $(wildcard include/config/nls/codepage/855.h) \
    $(wildcard include/config/nls/codepage/857.h) \
    $(wildcard include/config/nls/codepage/860.h) \
    $(wildcard include/config/nls/codepage/861.h) \
    $(wildcard include/config/nls/codepage/862.h) \
    $(wildcard include/config/nls/codepage/863.h) \
    $(wildcard include/config/nls/codepage/864.h) \
    $(wildcard include/config/nls/codepage/865.h) \
    $(wildcard include/config/nls/codepage/866.h) \
    $(wildcard include/config/nls/codepage/869.h) \
    $(wildcard include/config/nls/codepage/936.h) \
    $(wildcard include/config/nls/codepage/950.h) \
    $(wildcard include/config/nls/codepage/932.h) \
    $(wildcard include/config/nls/codepage/949.h) \
    $(wildcard include/config/nls/codepage/874.h) \
    $(wildcard include/config/nls/iso8859/8.h) \
    $(wildcard include/config/nls/codepage/1250.h) \
    $(wildcard include/config/nls/codepage/1251.h) \
    $(wildcard include/config/nls/ascii.h) \
    $(wildcard include/config/nls/iso8859/1.h) \
    $(wildcard include/config/nls/iso8859/2.h) \
    $(wildcard include/config/nls/iso8859/3.h) \
    $(wildcard include/config/nls/iso8859/4.h) \
    $(wildcard include/config/nls/iso8859/5.h) \
    $(wildcard include/config/nls/iso8859/6.h) \
    $(wildcard include/config/nls/iso8859/7.h) \
    $(wildcard include/config/nls/iso8859/9.h) \
    $(wildcard include/config/nls/iso8859/13.h) \
    $(wildcard include/config/nls/iso8859/14.h) \
    $(wildcard include/config/nls/iso8859/15.h) \
    $(wildcard include/config/nls/koi8/r.h) \
    $(wildcard include/config/nls/koi8/u.h) \
    $(wildcard include/config/nls/mac/roman.h) \
    $(wildcard include/config/nls/mac/celtic.h) \
    $(wildcard include/config/nls/mac/centeuro.h) \
    $(wildcard include/config/nls/mac/croatian.h) \
    $(wildcard include/config/nls/mac/cyrillic.h) \
    $(wildcard include/config/nls/mac/gaelic.h) \
    $(wildcard include/config/nls/mac/greek.h) \
    $(wildcard include/config/nls/mac/iceland.h) \
    $(wildcard include/config/nls/mac/inuit.h) \
    $(wildcard include/config/nls/mac/romanian.h) \
    $(wildcard include/config/nls/mac/turkish.h) \
    $(wildcard include/config/nls/utf8.h) \
    $(wildcard include/config/keys.h) \
    $(wildcard include/config/security/dmesg/restrict.h) \
    $(wildcard include/config/security.h) \
    $(wildcard include/config/securityfs.h) \
    $(wildcard include/config/default/security/dac.h) \
    $(wildcard include/config/default/security.h) \
    $(wildcard include/config/crypto.h) \
    $(wildcard include/config/crypto/fips.h) \
    $(wildcard include/config/crypto/algapi.h) \
    $(wildcard include/config/crypto/algapi2.h) \
    $(wildcard include/config/crypto/hash.h) \
    $(wildcard include/config/crypto/hash2.h) \
    $(wildcard include/config/crypto/rng.h) \
    $(wildcard include/config/crypto/rng2.h) \
    $(wildcard include/config/crypto/manager.h) \
    $(wildcard include/config/crypto/manager2.h) \
    $(wildcard include/config/crypto/user.h) \
    $(wildcard include/config/crypto/gf128mul.h) \
    $(wildcard include/config/crypto/null.h) \
    $(wildcard include/config/crypto/cryptd.h) \
    $(wildcard include/config/crypto/authenc.h) \
    $(wildcard include/config/crypto/test.h) \
    $(wildcard include/config/crypto/ccm.h) \
    $(wildcard include/config/crypto/gcm.h) \
    $(wildcard include/config/crypto/seqiv.h) \
    $(wildcard include/config/crypto/cbc.h) \
    $(wildcard include/config/crypto/ctr.h) \
    $(wildcard include/config/crypto/cts.h) \
    $(wildcard include/config/crypto/ecb.h) \
    $(wildcard include/config/crypto/lrw.h) \
    $(wildcard include/config/crypto/pcbc.h) \
    $(wildcard include/config/crypto/xts.h) \
    $(wildcard include/config/crypto/hmac.h) \
    $(wildcard include/config/crypto/xcbc.h) \
    $(wildcard include/config/crypto/vmac.h) \
    $(wildcard include/config/crypto/crc32c.h) \
    $(wildcard include/config/crypto/ghash.h) \
    $(wildcard include/config/crypto/md4.h) \
    $(wildcard include/config/crypto/md5.h) \
    $(wildcard include/config/crypto/michael/mic.h) \
    $(wildcard include/config/crypto/rmd128.h) \
    $(wildcard include/config/crypto/rmd160.h) \
    $(wildcard include/config/crypto/rmd256.h) \
    $(wildcard include/config/crypto/rmd320.h) \
    $(wildcard include/config/crypto/sha1.h) \
    $(wildcard include/config/crypto/sha256.h) \
    $(wildcard include/config/crypto/sha512.h) \
    $(wildcard include/config/crypto/tgr192.h) \
    $(wildcard include/config/crypto/wp512.h) \
    $(wildcard include/config/crypto/aes.h) \
    $(wildcard include/config/crypto/aes/x86/64.h) \
    $(wildcard include/config/crypto/anubis.h) \
    $(wildcard include/config/crypto/arc4.h) \
    $(wildcard include/config/crypto/blowfish.h) \
    $(wildcard include/config/crypto/camellia.h) \
    $(wildcard include/config/crypto/cast5.h) \
    $(wildcard include/config/crypto/cast6.h) \
    $(wildcard include/config/crypto/des.h) \
    $(wildcard include/config/crypto/fcrypt.h) \
    $(wildcard include/config/crypto/khazad.h) \
    $(wildcard include/config/crypto/salsa20.h) \
    $(wildcard include/config/crypto/salsa20/x86/64.h) \
    $(wildcard include/config/crypto/seed.h) \
    $(wildcard include/config/crypto/serpent.h) \
    $(wildcard include/config/crypto/tea.h) \
    $(wildcard include/config/crypto/twofish.h) \
    $(wildcard include/config/crypto/twofish/x86/64.h) \
    $(wildcard include/config/crypto/deflate.h) \
    $(wildcard include/config/crypto/zlib.h) \
    $(wildcard include/config/crypto/lzo.h) \
    $(wildcard include/config/crypto/ansi/cprng.h) \
    $(wildcard include/config/crypto/user/api/hash.h) \
    $(wildcard include/config/crypto/user/api/skcipher.h) \
    $(wildcard include/config/crypto/hw.h) \
    $(wildcard include/config/binary/printf.h) \
    $(wildcard include/config/bitreverse.h) \
    $(wildcard include/config/generic/find/first/bit.h) \
    $(wildcard include/config/generic/io.h) \
    $(wildcard include/config/percpu/rwsem.h) \
    $(wildcard include/config/crc/ccitt.h) \
    $(wildcard include/config/crc16.h) \
    $(wildcard include/config/crc/t10dif.h) \
    $(wildcard include/config/crc/itu/t.h) \
    $(wildcard include/config/crc32.h) \
    $(wildcard include/config/crc32/selftest.h) \
    $(wildcard include/config/crc32/sliceby8.h) \
    $(wildcard include/config/crc32/sliceby4.h) \
    $(wildcard include/config/crc32/sarwate.h) \
    $(wildcard include/config/crc32/bit.h) \
    $(wildcard include/config/crc7.h) \
    $(wildcard include/config/libcrc32c.h) \
    $(wildcard include/config/crc8.h) \
    $(wildcard include/config/xz/dec.h) \
    $(wildcard include/config/xz/dec/bcj.h) \
    $(wildcard include/config/dql.h) \
    $(wildcard include/config/nlattr.h) \
    $(wildcard include/config/average.h) \
    $(wildcard include/config/cordic.h) \
    $(wildcard include/config/ddr.h) \
    $(wildcard include/config/printk/time.h) \
    $(wildcard include/config/default/message/loglevel.h) \
    $(wildcard include/config/enable/warn/deprecated.h) \
    $(wildcard include/config/enable/must/check.h) \
    $(wildcard include/config/frame/warn.h) \
    $(wildcard include/config/strip/asm/syms.h) \
    $(wildcard include/config/readable/asm.h) \
    $(wildcard include/config/unused/symbols.h) \
    $(wildcard include/config/debug/fs.h) \
    $(wildcard include/config/debug/section/mismatch.h) \
    $(wildcard include/config/debug/kernel.h) \
    $(wildcard include/config/debug/shirq.h) \
    $(wildcard include/config/lockup/detector.h) \
    $(wildcard include/config/panic/on/oops.h) \
    $(wildcard include/config/panic/on/oops/value.h) \
    $(wildcard include/config/detect/hung/task.h) \
    $(wildcard include/config/sched/debug.h) \
    $(wildcard include/config/schedstats.h) \
    $(wildcard include/config/timer/stats.h) \
    $(wildcard include/config/debug/objects.h) \
    $(wildcard include/config/debug/slab.h) \
    $(wildcard include/config/debug/rt/mutexes.h) \
    $(wildcard include/config/rt/mutex/tester.h) \
    $(wildcard include/config/debug/spinlock.h) \
    $(wildcard include/config/debug/mutexes.h) \
    $(wildcard include/config/sparse/rcu/pointer.h) \
    $(wildcard include/config/debug/atomic/sleep.h) \
    $(wildcard include/config/debug/locking/api/selftests.h) \
    $(wildcard include/config/debug/stack/usage.h) \
    $(wildcard include/config/debug/kobject.h) \
    $(wildcard include/config/debug/bugverbose.h) \
    $(wildcard include/config/debug/info.h) \
    $(wildcard include/config/debug/info/reduced.h) \
    $(wildcard include/config/debug/vm.h) \
    $(wildcard include/config/debug/writecount.h) \
    $(wildcard include/config/debug/memory/init.h) \
    $(wildcard include/config/debug/list.h) \
    $(wildcard include/config/test/list/sort.h) \
    $(wildcard include/config/debug/sg.h) \
    $(wildcard include/config/debug/notifiers.h) \
    $(wildcard include/config/debug/credentials.h) \
    $(wildcard include/config/frame/pointer.h) \
    $(wildcard include/config/boot/printk/delay.h) \
    $(wildcard include/config/rcu/torture/test.h) \
    $(wildcard include/config/rcu/trace.h) \
    $(wildcard include/config/backtrace/self/test.h) \
    $(wildcard include/config/debug/block/ext/devt.h) \
    $(wildcard include/config/debug/force/weak/per/cpu.h) \
    $(wildcard include/config/notifier/error/injection.h) \
    $(wildcard include/config/fault/injection.h) \
    $(wildcard include/config/debug/pagealloc.h) \
    $(wildcard include/config/rbtree/test.h) \
    $(wildcard include/config/interval/tree/test.h) \
    $(wildcard include/config/atomic64/selftest.h) \
    $(wildcard include/config/samples.h) \
    $(wildcard include/config/test/kstrtox.h) \
    $(wildcard include/config/gprof.h) \
    $(wildcard include/config/gcov.h) \
    $(wildcard include/config/early/printk.h) \
  /home/valerian/Documents/ba6/OS/repo/Scheduler/linux-3.8.3/include/linux/kern_levels.h \
  /home/valerian/Documents/ba6/OS/repo/Scheduler/linux-3.8.3/arch/um/include/shared/user.h \
  include/generated/asm-offsets.h \
  /usr/lib/gcc/x86_64-linux-gnu/4.7/include/stddef.h \
  /usr/include/stdio.h \
  /usr/include/features.h \
  /usr/include/x86_64-linux-gnu/bits/predefs.h \
  /usr/include/x86_64-linux-gnu/sys/cdefs.h \
  /usr/include/x86_64-linux-gnu/bits/wordsize.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
  /usr/include/x86_64-linux-gnu/bits/types.h \
  /usr/include/x86_64-linux-gnu/bits/typesizes.h \
  /usr/include/libio.h \
  /usr/include/_G_config.h \
  /usr/include/wchar.h \
  /usr/lib/gcc/x86_64-linux-gnu/4.7/include/stdarg.h \
  /usr/include/x86_64-linux-gnu/bits/stdio_lim.h \
  /usr/include/x86_64-linux-gnu/bits/sys_errlist.h \
  /usr/include/x86_64-linux-gnu/bits/stdio2.h \
  /usr/include/stdlib.h \
  /usr/include/x86_64-linux-gnu/bits/waitflags.h \
  /usr/include/x86_64-linux-gnu/bits/waitstatus.h \
  /usr/include/endian.h \
  /usr/include/x86_64-linux-gnu/bits/endian.h \
  /usr/include/x86_64-linux-gnu/bits/byteswap.h \
  /usr/include/xlocale.h \
  /usr/include/x86_64-linux-gnu/sys/types.h \
  /usr/include/time.h \
  /usr/include/x86_64-linux-gnu/sys/select.h \
  /usr/include/x86_64-linux-gnu/bits/select.h \
  /usr/include/x86_64-linux-gnu/bits/sigset.h \
  /usr/include/x86_64-linux-gnu/bits/time.h \
  /usr/include/x86_64-linux-gnu/bits/select2.h \
  /usr/include/x86_64-linux-gnu/sys/sysmacros.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
  /usr/include/alloca.h \
  /usr/include/x86_64-linux-gnu/bits/stdlib.h \
  /home/valerian/Documents/ba6/OS/repo/Scheduler/linux-3.8.3/arch/um/include/shared/init.h \

arch/um/kernel/config.o: $(deps_arch/um/kernel/config.o)

$(deps_arch/um/kernel/config.o):
